agents/urls.py
from django.urls import path
from .views import AgentListView, AgentCreateView, AgentDetailView, AgentUpdateView, AgentDeleteView

app_name = "agents"

urlpatterns = [
    path('', AgentListView.as_view(), name='agent-list'),
    path('<int:pk>/', AgentDetailView.as_view(),name='agent-detail'),
    path('create/', AgentCreateView.as_view(), name='agent-create'),
    path('<int:pk>/update/', AgentUpdateView.as_view(), name= 'agent-update'),
    path('<int:pk>/delete/', AgentDeleteView.as_view(), name='agent-delete')

]

djcrm/urls.py
from django.conf import settings #Usando esta importación podemos hacer referencia a las variables como STATIC_URL y STATIC_ROOT
from django.conf.urls.static import static #Esta es una función que acepta dos cosas
from django.contrib import admin
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView
    )
from django.urls import path, include #ayuda a incluir el método include, que nos permite incluir la dirección del archivo urls.py de una app en específico
from leads.views import landing_page, LandingPageView, SignupView #importamos la vista del landing page de leads

'''urlpatterns es una lista de paths que existen en nuestra
aplicación web, indicando qué vista debe encargarse de eses path'''

'''Cuando una persona mete un url de nuestra página, se busca el path proporcionado en esta lista para ejecutar la función que se estableció como segundo argumento'''
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPageView.as_view(), name='landing-page'),
    path('leads/', include('leads.urls', namespace="leads")), 
    #Si alguien entra al path leads/ de nuestra página, django va a buscar dentro de la carpeta leads el archivo urls que se encuentra en el archivo leads.
    path('agents/', include('agents.urls', namespace="agents")),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name = 'logout'),
    path('signup/', SignupView.as_view(), name='signup'),
    path('reset-password/', PasswordResetView.as_view(), name='reset-password'),
    path('password-reset-done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'), #La vista revisa que uidb64 y token estén en el url, de lo contrario lanza un error. NECESITA TENER AMBOS EN UN URL PARA QUE SEA VÁLIDO PODER CAMBIAR LA CONTRASEÑA
    path('password-reset-complete', PasswordResetCompleteView.as_view(), name='password_reset_complete') 
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

agents/models.py
from django.db import models

# Create your models here.

agents/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm #Ya existe un form para crear usuarios

User = get_user_model()

class AgentModelForm(forms.ModelForm):
    class Meta:
        model = User
        fields = (
            'email',
            'username',
            'first_name',
            'last_name'
        )
        #Este form crearía un nuevo usuario, no un nuevo agente

agents/views.py
import random
from typing import Any
from django.db.models.query import QuerySet
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.mail import send_mail
from django.shortcuts import reverse
from leads.models import Agent
from .forms import AgentModelForm
from .mixins import OrganisorAndLoginRequiredMixin

class AgentListView(OrganisorAndLoginRequiredMixin, generic.ListView):
    template_name = "agents/agent_list.html"
    context_object_name = "agent"
    
    def get_queryset(self):
        organisation = self.request.user.userprofile
        #Esta parte toma el usuario que esta logeado. La parte de userprofile toma al Modelo UserProfile del usuario que esta logeado. La relación que tiene esto en el agente es de una llave foránea al modelo UserProfile. De esta manera se van a filtrar los agentes de acuerdo con el campo de organisation
        return Agent.objects.filter(organisation=organisation)#Podemos filtrar nuestros agentes de acuerdo con 2 campos definidos en el modelo de agente: user y organisation. "Regresame los objetos de agente, en los cuales el organisation es igual al organisation del usuario que los está solicitando"
    
class AgentCreateView(OrganisorAndLoginRequiredMixin, generic.CreateView): #Esta vista va a crear un usuario y automáticamente crea al agente, enviándole un  correo confirmando su incorporación al equipo
    template_name = "agents/agent_create.html"
    form_class = AgentModelForm

    def get_success_url(self):
        return reverse("agents:agent-list")
    
    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_agent = True
        user.is_organisor = False
        user.set_password(f"{random.randint(100000,1000000000)}") #El valor que se encuentra adentro del paréntesis debe ser un string. En nuestro caso elegimos una contraseña default aleatoria. set_password automáticamente hashea la contraseña
        user.save()
        Agent.objects.create( #Una vez que se guarda el usuario, se guarda el agente con el usuario igual al usuario creado, y la organisasion igual a la del usuario que está creando el perfil.
            user=user,
            organisation= self.request.user.userprofile
        )
        send_mail(
            subject="You are invited to be an agent!",
            message="You were added as an agent on DJCRM. Please login to start working",
            from_email = "admin@test.com",
            recipient_list = [user.email],
        )
        #agent.organisation = self.request.user.userprofile #Se guarda el agente debajo del userprofile que lo está creando
        #agent.save()
        return super(AgentCreateView, self).form_valid(form)
    
class AgentDetailView(OrganisorAndLoginRequiredMixin, generic.DetailView):
    template_name = "agents/agent_detail.html"
    context_object_name = "agent" #Especificamos el context object para que sea agent

    def get_queryset(self):
        organisation = self.request.user.userprofile
        return Agent.objects.filter(organisation=organisation)

class AgentUpdateView(OrganisorAndLoginRequiredMixin, generic.UpdateView):
    template_name = "agents/agent_update.html"
    form_class = AgentModelForm

    def get_success_url(self):
        return reverse("agents:agent-list") #CADA VEZ QUE VAYAMOS A CREAR, MODIFICAR O ELIMINAR ALDO DE UN QUERYSET DE LA BASE DE DATOS, DEBEMOS PROPORCIONAR UN GET_SUCCESS_URL PARA QUE SE LLEVE A CABO DE LA MANERA ADECUADA
    
    def get_queryset(self):
        organisation = self.request.user.userprofile
        return Agent.objects.filter(organisation=organisation)
    
class AgentDeleteView(OrganisorAndLoginRequiredMixin, generic.DeleteView):
    template_name = "agents/agent_delete.html"
    context_object_name = "agent" #Especificamos el context object para que sea agent

    def get_success_url(self):
        return reverse("agents:agent-list")
    
    def get_queryset(self):
        organisation = self.request.user.userprofile
        return Agent.objects.filter(organisation=organisation)

agents/templates/agents/agent_create.html
{% extends "base.html" %}

{% block content %}
        <a href="{% url 'agents:agent-list' %}">Agents</a>
        <hr />
        <h1>Create a new agent</h1>
        <form method="post" action=""><!--Se coloca 'method="post"' porque indica que se va a agregar un lead, por ende we are posting a new set of information.
        
        Se coloca action para indicar a que path se va a enviar la información que se está ingresando-->

        {%csrf_token%}<!--Esto es un aspecto de seguridad que se tiene que cumplir para cuando se este posteando información-->
        {{form}}
        <button type="submit">Submit</button>
        </form>

{% endblock content %}

agents/templates/agents/agent_delete.html
{% extends "base.html" %}

{% block content %}
        <a href="{% url 'agents:agent-list' %}">agents</a>
        <hr />
        <h1>¿Are you sure you want to delete this agent?</h1>
        <form method="post" action=""><!--Se coloca 'method="post"' porque indica que se va a agregar un agent, por ende we are posting a new set of information.
        
        Se coloca action para indicar a que path se va a enviar la información que se está ingresando-->

        {%csrf_token%}<!--Esto es un aspecto de seguridad que se tiene que cumplir para cuando se este posteando información-->
        {{form}}
        <button type="submit">Submit</button>
        </form>

{% endblock content %}

agents/templates/agents/agent_detail.html
{% extends "base.html" %}

{% block content %}

<section class="text-gray-700 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
      <div class="lg:w-4/5 mx-auto flex flex-wrap">
        <div class="w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
            <h2 class="text-sm title-font text-gray-500 tracking-widest">AGENT</h2>
            <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ agent.user.username }}</h1>
            <div class="flex mb-4">
                <a href="{% url 'agents:agent-detail' agent.pk %}" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">
                    Overview
                </a>
                <a href="{% url 'agents:agent-update' agent.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                    Update Details
                </a>    
            </div>
            <div class="flex border-t border-gray-300 py-2">
                <span class="text-gray-500">Full Name</span>
                <span class="ml-auto text-gray-900">{{ agent.user.first_name }} {{ agent.user.last_name }}</span>
            </div>
            <div class="flex border-t border-gray-300 py-2">
                <span class="text-gray-500">Email</span>
                <span class="ml-auto text-gray-900">{{ agent.user.email }}</span>
            </div>
        </div>
      </div>
    </div>
  </section>
{% endblock content %}

agents/templates/agents/agent_list.html
{% extends "base.html" %}

{% block content %}

    <h1>Here are our agents</h1>


    
<section class="text-gray-600 body-font">
  <div class="container px-5 py-24 mx-auto flex flex-wrap">
        <div class="w-full mb-6 py-6 flex justify-between items-center border-b border-gray-200">
            <div>
                <h1 class="text-4xl text-gray-800">Agents</h1>
            </div>
            <div>
                <a class="text-gray-500 hover:text-blue-500"href="{% url 'agents:agent-create' %}">Create a new agent</a>
            </div>
        </div>
    <div class="flex flex-wrap -m-4">
        {%for agent in object_list%}
      <div class="p-4 lg:w-1/2 md:w-full">
        <div class="flex border-2 rounded-lg border-gray-200 border-opacity-50 p-8 sm:flex-row flex-col">
          <div class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 flex-shrink-0">
            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-8 h-8" viewBox="0 0 24 24">
              <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
            </svg>
          </div>
          <div class="flex-grow">
            <h2 class="text-gray-900 text-lg title-font font-medium mb-3">
            {{agent.user.username}}
            </h2>
            <p class="leading-relaxed text-base">
            Blue bottle crucifix vinyl post-ironic four dollar toast vegan taxidermy. Gastropub indxgo juice poutine.
            </p>
            <a href="{% url 'agents:agent-detail' agent.pk %}" class="mt-3 text-indigo-500 inline-flex items-center">
            View this agent <!--Le colocamos un hipervínculo al nombre y apellido del lead para poder navegar dentro de la misma página para poder observar su información-->
              <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                <path d="M5 12h14M12 5l7 7-7 7"></path>
              </svg>
            </a>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</section>
{% endblock content %}

agents/templates/agents/agent_update.html
{% extends "base.html" %}

{% block content %}

<section class="text-gray-600 body-font overflow-hidden">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-4/5 mx-auto flex flex-wrap">
      <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
        <h2 class="text-sm title-font text-gray-500 tracking-widest">AGENT</h2>
        <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{agent.user.username}}</h1>
        <div class="flex mb-4">
          <a href="{% url 'agents:agent-detail' agent.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
          Overview
          </a>
          <a class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
          Reviews
          </a>
          <a href="{% url 'agents:agent-update' agent.pk %}" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">
          Update Details
          </a>
        </div>
         <form method="post" action=""><!--Se coloca 'method="post"' porque indica que se va a agregar un agent, por ende we are posting a new set of information.
        
        Se coloca action para indicar a que path se va a enviar la información que se está ingresando-->

        {%csrf_token%}<!--Esto es un aspecto de seguridad que se tiene que cumplir para cuando se este posteando información-->
        {{form}}
        <button type="submit">Submit</button>
        </form>
        <a href="{% url 'agents:agent-delete' agent.pk %}" class="w-1/2 mt-3 flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">Delete</a> <!--mt-3 sirve para bajar un campo-->
      </div>
      <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="https://dummyimage.com/400x400">
    </div>
  </div>
</section>

         <!--<a href="{% url 'agents:agent-list' %}">agents</a>
        <hr />
        <h1>These are the details of {{agent.first_name}}</h1>
        <p>This person´s age: {{agent.age}}</p>
        <p>The agent responsible for this agent is: {{agent.agent}}</p>
        <hr />
        <a href="{% url 'agents:agent-update' agent.pk %}">Update</a>
        <a href="#">Delete</a>

       <a href="{% url 'agents:agent-detail' agent.pk %}">Go back to {{agent.first_name}} {{agent.last_name}}</a>
        <hr />
        <h1>Update agent: {{agent.first_name}} {{agent.last_name}}</h1>-->
       
{% endblock content %}
 