agents/urls.py
from django.urls import path
from .views import AgentListView, AgentCreateView, AgentDetailView, AgentUpdateView, AgentDeleteView

app_name = "agents"

urlpatterns = [
    path('', AgentListView.as_view(), name='agent-list'),
    path('<int:pk>/', AgentDetailView.as_view(),name='agent-detail'),
    path('create/', AgentCreateView.as_view(), name='agent-create'),
    path('<int:pk>/update/', AgentUpdateView.as_view(), name= 'agent-update'),
    path('<int:pk>/delete/', AgentDeleteView.as_view(), name='agent-delete')

]

djcrm/urls.py
from django.conf import settings #Usando esta importación podemos hacer referencia a las variables como STATIC_URL y STATIC_ROOT
from django.conf.urls.static import static #Esta es una función que acepta dos cosas
from django.contrib import admin
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView
    )
from django.urls import path, include #ayuda a incluir el método include, que nos permite incluir la dirección del archivo urls.py de una app en específico
from leads.views import landing_page, LandingPageView, SignupView #importamos la vista del landing page de leads

'''urlpatterns es una lista de paths que existen en nuestra
aplicación web, indicando qué vista debe encargarse de eses path'''

'''Cuando una persona mete un url de nuestra página, se busca el path proporcionado en esta lista para ejecutar la función que se estableció como segundo argumento'''
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPageView.as_view(), name='landing-page'),
    path('leads/', include('leads.urls', namespace="leads")), 
    #Si alguien entra al path leads/ de nuestra página, django va a buscar dentro de la carpeta leads el archivo urls que se encuentra en el archivo leads.
    path('agents/', include('agents.urls', namespace="agents")),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name = 'logout'),
    path('signup/', SignupView.as_view(), name='signup'),
    path('reset-password/', PasswordResetView.as_view(), name='reset-password'),
    path('password-reset-done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'), #La vista revisa que uidb64 y token estén en el url, de lo contrario lanza un error. NECESITA TENER AMBOS EN UN URL PARA QUE SEA VÁLIDO PODER CAMBIAR LA CONTRASEÑA
    path('password-reset-complete', PasswordResetCompleteView.as_view(), name='password_reset_complete') 
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

leads/urls.py
from django.urls import path
from .views import (lead_list, lead_detail, lead_create, lead_update, lead_delete, LeadListView, LeadDetailView, LeadCreateView, LeadUpdateView, LeadDeleteView)

app_name = "leads" #Se le tiene que dar un nombre para que se pueda incluir la referencia a este archivo en el urls.py de djcrm. Entonces, cuando alguien entre al url ...leads/..., va a buscar la dirección dentro de esta carpeta

urlpatterns = [
    path('', LeadListView.as_view(), name='lead-list'),#Cuando alguien quiere ingresar al camino default de nuestra página, Django responde con la función home_page establecida en views.py de lead, la cual recibe un request y se ejecuta de acuerdo a lo establecido

    path('create/', LeadCreateView.as_view(), name='lead-create'),

    path('<int:pk>/', LeadDetailView.as_view(), name='lead-detail'),#cuando se introduzca una llave primaria en el path del url, este llama a la vista lead_detail para mostrar la información de aquel lead que corresponda con la llave primaria ingresada

    #Tenemos que poner el path de '<pk>/' hasta abajo para que django no interprete que cualquier otro path es una llave primaria. O podemos establecer que una llave primaria es un numero entero, de esta manera django solo accede al path '<pk>/' si es un entero
    path('<int:pk>/update/', LeadUpdateView.as_view(), name= 'lead-update'),
    path('<int:pk>/delete/', LeadDeleteView.as_view(), name='lead-delete')
]

#Con el name=... se le da un nombre al url, y lo que nos permite esto es referenciar cada uno de los paths de manera más facil. Por ejemplo, en los templates, si se quiere colocar un <a href"..."></a>, se puede colocar el nombre del path que asignamos en caso que el "hard-coded link" se llegue a modificar

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>DJCRM</title>
        <link href="{% static 'CSS/styles.css' %}" rel="stylesheet"/>
        <script src="https://cdn.tailwindcss.com"></script>
    </head>
    <body>
        <div class="max-w-7xl">
        {% include "navbar.html" %}
        {% block content %}
        {% endblock content %}
        </div>
        {% include "scripts.html" %}
        <!--Tambien podemos generalizar scripts que pueden ser heredados por otros archivos .html-->
    </body>
</html>
<!--Este archivo html sirve para crear una estructura base para poder utilizar en otros scripts, los cuales heredan todo lo que se ve en la parte de arriba-->

templates/landing.html
{% extends "base.html" %}

{% block  content%}

<section class="text-gray-600 body-font">
  <div class="container mx-auto flex px-5 py-24 items-center justify-center flex-col">
    <img class="lg:w-2/6 md:w-3/6 w-5/6 mb-10 object-cover object-center rounded" alt="hero" src="https://dummyimage.com/720x600">
    <div class="text-center lg:w-2/3 w-full">
      <h1 class="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900">CRM built with Django</h1>
      <p class="mb-8 leading-relaxed">Este CRM te ayuda a gestionar tus leads</p>
      <div class="flex justify-center">
        <button class="inline-flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg">Button</button>
        <button class="ml-4 inline-flex text-gray-700 bg-gray-100 border-0 py-2 px-6 focus:outline-none hover:bg-gray-200 rounded text-lg">Button</button>
      </div>
    </div>
  </div>
</section>

{% endblock content %}

templates/lead_create.html
{% extends "base.html" %}

{% block content %}
        <a href="{% url 'leads:lead-list' %}">leads</a>
        <hr />
        <h1>Create a new lead</h1>
        <form method="post" action=""><!--Se coloca 'method="post"' porque indica que se va a agregar un lead, por ende we are posting a new set of information.
        
        Se coloca action para indicar a que path se va a enviar la información que se está ingresando-->

        {%csrf_token%}<!--Esto es un aspecto de seguridad que se tiene que cumplir para cuando se este posteando información-->
        {{form}}
        <button type="submit">Submit</button>
        </form>

{% endblock content %}

templates/lead_delete.html
{% extends "base.html" %}

{% block content %}
        <a href="{% url 'leads:lead-list' %}">leads</a>
        <hr />
        <h1>¿Are you sure you want to delete this lead?</h1>
        <form method="post" action=""><!--Se coloca 'method="post"' porque indica que se va a agregar un lead, por ende we are posting a new set of information.
        
        Se coloca action para indicar a que path se va a enviar la información que se está ingresando-->

        {%csrf_token%}<!--Esto es un aspecto de seguridad que se tiene que cumplir para cuando se este posteando información-->
        {{form}}
        <button type="submit">Submit</button>
        </form>

{% endblock content %}

templates/lead_detail.html
{% extends "base.html" %}

{% block content %}

<section class="text-gray-600 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
        <div class="lg:w-4/5 mx-auto flex flex-wrap">
            <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
                <h2 class="text-sm title-font text-gray-500 tracking-widest">LEAD</h2>
                <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{lead.first_name}} {{lead.last_name}}</h1>
                <div class="flex mb-4">
                    {% if lead %}
                        <a href="{% url 'leads:lead-detail' lead.pk %}" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">
                            Overview
                        </a>
                    {% endif %}
                    <a class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                        Reviews
                    </a>
                    <a href="{% url 'leads:lead-update' lead.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                        Update Details
                    </a>
                </div>
                <p class="leading-relaxed mb-4">Fam locavore kickstarter distillery. Mixtape chillwave tumeric sriracha taximy chia microdosing tilde DIY. XOXO fam inxigo juiceramps cornhole raw denim forage brooklyn. Everyday carry +1 seitan poutine tumeric. Gastropub blue bottle austin listicle pour-over, neutra jean.</p>
                <div class="flex border-t border-gray-200 py-2">
                    <span class="text-gray-500">Age</span>
                    <span class="ml-auto text-gray-900">{{lead.age}}</span>
                </div>
                <div class="flex border-t border-gray-200 py-2">
                    <span class="text-gray-500">Location</span>
                    <span class="ml-auto text-gray-900">Dummy location</span>
                </div>
                <div class="flex border-t border-b mb-6 border-gray-200 py-2">
                    <span class="text-gray-500">Cell phone</span>
                    <span class="ml-auto text-gray-900">0883849287342</span>
                </div>
                <div class="flex">
                    <button class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">Button</button>
                    <button class="rounded-full w-10 h-10 bg-gray-200 p-0 border-0 inline-flex items-center justify-center text-gray-500 ml-4">
                        <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
                            <path d="M20.84 4.61a5.5 5.5 0 00-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 00-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 000-7.78z"></path>
                        </svg>
                    </button>
                </div>
            </div>
            <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="https://dummyimage.com/400x400">
        </div>
    </div>
</section>

{% endblock content %}

templates/lead_list.html
{% extends "base.html" %}

{% block content %}

<section class="text-gray-600 body-font">
  <div class="container px-5 py-24 mx-auto flex flex-wrap">
        <div class="w-full mb-6 py-6 flex justify-between items-center border-b border-gray-200">
            <div>
                <h1 class="text-4xl text-gray-800">Leads</h1>
            </div>
            {% if request.user.is_organisor %}
            <div>
                <a class="text-gray-500 hover:text-blue-500"href="{% url 'leads:lead-create' %}">Create a new lead</a>
            </div>
            {% endif %}
        </div>
    <div class="flex flex-wrap -m-4">
        {%for lead in leads%}
      <div class="p-4 lg:w-1/2 md:w-full">
        <div class="flex border-2 rounded-lg border-gray-200 border-opacity-50 p-8 sm:flex-row flex-col">
          <div class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 flex-shrink-0">
            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-8 h-8" viewBox="0 0 24 24">
              <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
            </svg>
          </div>
          <div class="flex-grow">
            <h2 class="text-gray-900 text-lg title-font font-medium mb-3">
            {{lead.first_name}} {{lead.last_name}}
            </h2>
            <p class="leading-relaxed text-base">
            Blue bottle crucifix vinyl post-ironic four dollar toast vegan taxidermy. Gastropub indxgo juice poutine.
            </p>
            <a href="{% url 'leads:lead-detail' lead.pk %}" class="mt-3 text-indigo-500 inline-flex items-center">
            View this lead <!--Le colocamos un hipervínculo al nombre y apellido del lead para poder navegar dentro de la misma página para poder observar su información-->
              <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                <path d="M5 12h14M12 5l7 7-7 7"></path>
              </svg>
            </a>
          </div>
        </div>
      </div>
      {%endfor%}
    </div>
  </div>
</section>
{% endblock content %}

templates/lead_update.html
{% extends "base.html" %}

{% block content %}

<section class="text-gray-600 body-font overflow-hidden">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-4/5 mx-auto flex flex-wrap">
      <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
        <h2 class="text-sm title-font text-gray-500 tracking-widest">LEAD</h2>
        <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{lead.first_name}} {{lead.last_name}}</h1>
        <div class="flex mb-4">
          <a href="{% url 'leads:lead-detail' lead.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
          Overview
          </a>
          <a class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
          Reviews
          </a>
          <a href="{% url 'leads:lead-update' lead.pk %}" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">
          Update Details
          </a>
        </div>
         <form method="post" action=""><!--Se coloca 'method="post"' porque indica que se va a agregar un lead, por ende we are posting a new set of information.
        
        Se coloca action para indicar a que path se va a enviar la información que se está ingresando-->

        {%csrf_token%}<!--Esto es un aspecto de seguridad que se tiene que cumplir para cuando se este posteando información-->
        {{form}}
        <button type="submit">Submit</button>
        </form>
        <a href="{% url 'leads:lead-delete' lead.pk %}" class="w-1/2 mt-3 flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">Delete</a> <!--mt-3 sirve para bajar un campo-->
      </div>
      <img alt="ecommerce" class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded" src="https://dummyimage.com/400x400">
    </div>
  </div>
</section>

         <!--<a href="{% url 'leads:lead-list' %}">leads</a>
        <hr />
        <h1>These are the details of {{lead.first_name}}</h1>
        <p>This person´s age: {{lead.age}}</p>
        <p>The agent responsible for this lead is: {{lead.agent}}</p>
        <hr />
        <a href="{% url 'leads:lead-update' lead.pk %}">Update</a>
        <a href="{% url 'leads:lead-delete' lead.pk %}">Delete</a>

       <a href="{% url 'leads:lead-detail' lead.pk %}">Go back to {{lead.first_name}} {{lead.last_name}}</a>
        <hr />
        <h1>Update lead: {{lead.first_name}} {{lead.last_name}}</h1>-->
       
{% endblock content %}
 

templates/navbar.html
<header class="text-gray-600 body-font">
  <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
    <a class="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0">
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-10 h-10 text-white p-2 bg-indigo-500 rounded-full" viewBox="0 0 24 24">
        <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"></path>
      </svg>
      <span class="ml-3 text-xl">CRM</span>
    </a>
    <nav class="md:ml-auto flex flex-wrap items-center text-base justify-center">
      
      {% if not request.user.is_authenticated%}

      <a href= "{% url 'signup' %}" class="mr-5 hover:text-gray-900">Signup</a>

        {% else %} <!--Este else nos muestra los links de abajo únicamente si estamos logeados dentro de la página-->
        <a href="{% url 'leads:lead-list' %}" class="mr-5 hover:text-gray-900">Leads</a> <!--Este link nos lleva la página de la lista de los leads-->


        {% if request.user.is_organisor %}
        <a href="{% url 'agents:agent-list' %}" class="mr-5 hover:text-gray-900">Agents</a> <!--Este link nos lleva la página de la lista de los agentes-->
        {% endif %} <!--Este if revisa si el usuario es o no un organisor. Si lo es entonces si se muestra, de lo contrario no se muestra el link-->


      {% endif %}
      <!--Este if nos muestra la opción de crear una sesión si todavía no lo hemos hecho-->

    </nav>

    {% if request.user.is_authenticated%}
      Logged in as: {{ request.user.username }}
      <a href= "{% url 'logout' %}" class="ml-3 inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0">
        Logout
      <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
        <path d="M5 12h14M12 5l7 7-7 7"></path>
      </svg>
    </a>

    {% else %}
      <a href= "{% url 'login' %}" class="inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0">
          Login
        <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
          <path d="M5 12h14M12 5l7 7-7 7"></path>
        </svg>
      </a>
    {% endif %}
    <!--Este if nos ayuda a que se muestre el boton de login si no lo hemos hecho, y muestra el boton de logout si ya tenemos una sesión iniciada-->
  </div>
</header>

templates/scripts.html
{% load static %}

<script src="{% static 'JS/main.js' %}">
    console.log("hello")
</script>